[build]
  functions = "functions-build"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "functions-build"

  
[build.environment]
NODE_VERSION = "18.20.4"
